Added an option to block steam accounts that have not yet setup their profile. Also added config options to edit the kick messages players receive.
KarlOfDuty/VPNShield pull request #6
Opened 2019-10-18 20:57 UTC by Cyanox62

Added in config.json
- `"block-non-setup-steam-accounts"` - Bool that can be set in the config just like any other config option. Blocks steam accounts that have not yet been setup. Current users of the plugin will be required to add this line manually.

Added in SCP config
- `vs_no_purchases_message` - Determines the message to be displayed to a user when they are kicked for not having any purchases on their account.
- `vs_non_setup_message` - Determines the message to be displayed to a user when they are kicked for not having their steam profile setup.

Bumped version number `3.2.0` -> `3.3.0`

2019-10-18 23:25 UTC, KarlOfDuty requested changes

2019-10-18 23:25 UTC, KarlOfDuty commented on VPNShield/VPNShield.cs
> +			this.AddConfig(new ConfigSetting("vs_non_setup_message", "This server does not allow non setup Steam accounts, you have to setup your Steam profile before playing.", true, "The message to display
These should not be vanilla config options, they should be part of the plugin config.

2019-10-18 23:25 UTC, KarlOfDuty commented on VPNShield/VPNShield.cs
> +		public string noPurchaseKick;
This file is inconsistent with tabs/spaces, please convert the file to use space indentation to remove this issue.

2019-10-18 23:27 UTC, KarlOfDuty commented
Thanks for the PR, I think that could be pretty useful for the plugin! I just need you to change the above before I merge it.

2019-10-19 07:01 UTC, Cyanox62 commented
I've changed the configs to be in the json file instead and fixed the spacing. I also added a config validator so that players updating their plugin should just be able to drag and drop and it'll fix their config with the new options automatically. So you can disregard what I said above about having to manually add that new line.

2019-10-29 18:35 UTC, KarlOfDuty commented
Sounds good, but you still need to fix the whitespace issues
![image](https://user-images.githubusercontent.com/18099825/67798096-35b19100-fa83-11e9-83fb-e2d7306a815b.png)

2019-10-29 18:36 UTC, KarlOfDuty requested changes
As per previous comment, the whitespace is messed up.

2019-11-01 22:51 UTC, merged